server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
        git:
            uri: https://github.com/ramonnteixeira/unibave-config-repo
  rabbitmq:
    host: localhost
    port: 5672    